set columns=120
set lines=50

if has('gui_running')
    " Disable toolbar
    set go-=T
  " MacVim specific confguration
  if has("gui_macvim")
    " MacVim font
    set guifont=Menlo:h12
  else
    set guifont=Monospace\ 9
  endif
endif

