# Path to your oh-my-zsh installation.
# oh-my-zsh installation
# git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
export ZSH=$HOME/.oh-my-zsh

# trsan theme configuration.
# Set this with your own host names to enable different prompt colors per host
# group.
PROD_HOSTS=( )
PROD_HOSTS_COLOR="red"
DEV_HOSTS=( blashyrkh )
DEV_HOSTS_COLOR="cyan"
PRIVATE_HOSTS=( delirium havoc nemesis )
PRIVATE_HOSTS_COLOR="green"
OTHER_HOSTS_COLOR="white"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="trsan"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(colordiff cp encode64 git jsontools mailcheck torrent urltools)

source $ZSH/oh-my-zsh.sh

# User configuration

# Paths
export PATH=$HOME/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# Locale
# If locale is not set, set it to en_US.UTF-8 as default
if [ -z "$LANGUAGE" ]; then
    export LANGUAGE=en_US.UTF-8
fi

if [ -z "$LANG" ]; then
    export LANG=en_US.UTF-8
fi

if [ -z "$LC_ALL" ]; then
    export LC_ALL=en_US.UTF-8
fi

# Use viins key binding
#bindkey -v

setopt  EXTENDED_GLOB NOMATCH
unsetopt AUTOCD NOTIFY

# History
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000000
# do not save duplicate command to history
setopt HIST_SAVE_NO_DUPS
# remove superfluous blanks from each command line
setopt HIST_REDUCE_BLANKS
# if a line starts with a space, don't save it
setopt HIST_IGNORE_SPACE
# remove the history (fc -l) command from the history
setopt HIST_NO_STORE
# append rather than overwrite history file
setopt APPEND_HISTORY
# share history between multiple shells
setopt SHARE_HISTORY
# save timestamp and runtime information
setopt EXTENDED_HISTORY

# Terminal colors
# enable terminal colors for Mac OS X
#export CLICOLOR=1

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
#
# Always use vim editor
export EDITOR=vim

# set default editor for SVN
export SVN_EDITOR=vim

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

